version: "3.8"

services:
  db:
    image: postgres:15.3
    environment:
      - "POSTGRES_PASSWORD=password"

  api:
    env_file:
      - docker-compose-args.env
    build: ./planner-api
    image: planner-api:latest
    depends_on:
      - db
    ports:
      - "8080:8080"

  ui:
    build: ./planner-ui
    depends_on:
      - api
    image: planner-ui:latest
    ports:
      - "3000:80"
