version: 2.1
executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

orbs:
  node: circleci/node@5.0.3
  maven: circleci/maven@1.4.0

jobs:
  ui_format:
    working_directory: planner-ui
    docker:
      - image: cimg/node:16.13
    resource_class: small
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          cache-version: v2
      - run: npm run check-format-strict:planner-ui

  ui_test:
    working_directory: planner-ui
    docker:
      - image: cimg/node:16.13
    resource_class: small
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          cache-version: v2
      - run:
          name: Run tests
          command: npm test -- --ci --reporters=default --reporters=jest-junit --coverage --maxWorkers=2
      - store_test_results:
          path: ~/project/planner-ui/junit.xml
      - store_artifacts:
          path: ./coverage/

  ui:
    working_directory: planner-ui
    docker:
      - image: cimg/node:16.13
    resource_class: small
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          cache-version: v2
      - run: npm run build

  api_format:
    working_directory: planner-api
    executor: maven/default
    resource_class: small
    steps:
      - checkout:
          path: ~/project
      - maven/with_cache:
          steps:
          - run: mvn spotless:check
#   api:
#     working_directory: planner-api
#     executor: maven/default
#     resource_class: small
#     steps:
#       - checkout:
#           path: ~/project
#       - maven/with_cache:
#           steps:
#             - run: 
#                 command: mvn test
#                 executor: java17
#             - store_artifacts:
#                 path: target/site/jacoco
#             - run:
#                 name: Save test store_test_results
#                 command: 
#                   mkdir -p ~/test-results/junit/
#                   find . -type f -regex ".*/target/surefire-reports.*xml" -exec cp {} ~/test-results/junit/ \;
#             - store_test_results:
#                 path: ~/test-results/junit/

workflows:
  ui: 
    jobs:
      - ui_format
      - ui_test
      - ui:
          requires:
            - ui_format
            - ui_test
  api:
    jobs:
      - api_format
      - maven/test:
          app_src_directory: planner-api
          executor: java17
