version: 2.1
executors:
  machine_executor:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

orbs:
  node: circleci/node@5.0.3
  maven: circleci/maven@1.4.0

jobs:
  ui_format:
    working_directory: planner-ui
    docker:
      - image: cimg/node:16.13
    resource_class: small
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          cache-version: v2
      - run: npm run check-format-strict:ui

  ui_test:
    working_directory: planner-ui
    docker:
      - image: cimg/node:16.13
    resource_class: small
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          cache-version: v2
      - run:
          name: Run tests
          command: npm test -- --ci --reporters=default --reporters=jest-junit --coverage --maxWorkers=2
      - store_test_results:
          path: ~/project/planner-ui/junit.xml
      - store_artifacts:
          path: ./coverage/

  ui:
    working_directory: planner-ui
    docker:
      - image: cimg/node:16.13
    resource_class: small
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          cache-version: v2
      - run: npm run build

  api_format:
    working_directory: planner-api
    executor: maven/default
    resource_class: small
    steps:
      - checkout:
          path: ~/project
      - maven/with_cache:
          steps:
            - run: mvn spotless:check
  api_build_and_test:
    working_directory: planner-api
    executor: machine_executor
    steps:
      - checkout:
          path: ~/project
      - run: mvn -B clean install -Dspring.profiles.active=test
      - maven/with_cache:
          steps:
            - run: mvn test -Dspring.profiles.active=test

workflows:
  ui:
    jobs:
      - ui
  api:
    jobs:
      - api_format
      - api_build_and_test
