spring:
  datasource:
    url: jdbc:h2:mem:mealplannerdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console.enabled: true
    console.path: /h2

data.loader:
  onStart: true
  filetype: csv
  ingredients: initialdata/data-ingredients.csv
  recipes: initialdata/data-recipes.csv
