server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger.html

spring:
  datasource:
    url: jdbc:h2:mem:mealplannerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true
    console.path: /h2
  jpa:
    hibernate:
      dll-auto: validate