spring.profiles.active: dev

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger.html

spring.jpa.hibernate.dll-auto: validate
