spring:
  datasource:
    url: jdbc:h2:mem:mealplannerdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console.enabled: true
    console.path: /h2

data.loader:
  onStart: true
  filetype: csv
  ingredients: initialdata/data-ingredients.csv
  recipes: initialdata/data-recipes.csv

authentication:
  toggle: true
  jwt:
    secretKey: a16af43fb94395491d4d27d5d913ec3d82024887d7edb44124ff45b9da058b53

admin:
  username: "admin"
  password: "admin"
