server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger.html

spring.jpa.hibernate.dll-auto: validate

authentication:
  jwt:
    expiration: 86400000 # 1 day
    refresh-token:
      expiration: 604800000 # 7 days
